package export

import (
	"fmt"
	"strings"
)

// Cloudflare Pages / Workers static-assets limits for _redirects. Both
// products parse the same files with the same limits. Every redirect
// signpost emits is a static (no splat/placeholder) rule.
const (
	cloudflareMaxStaticRedirects = 2000
	cloudflareMaxRedirectLine    = 1000
)

// cloudflareTarget writes _redirects and _headers at the output root.
// Neither file is served; the host parses them at deploy time.
type cloudflareTarget struct{}

func (cloudflareTarget) Name() string { return "cloudflare" }

func (cloudflareTarget) Emit(m *Manifest) (map[string][]byte, error) {
	if n := len(m.Redirects); n > cloudflareMaxStaticRedirects {
		return nil, fmt.Errorf("%d redirects exceeds the _redirects limit of %d static rules", n, cloudflareMaxStaticRedirects)
	}
	var rd strings.Builder
	rd.WriteString("# Generated by signpost export. Do not edit; the next export overwrites this file.\n")
	rd.WriteString("# <pool path> <upstream .deb URL> 302\n")
	for _, r := range m.Redirects {
		line := fmt.Sprintf("%s %s %d", r.Path, r.Location, r.Status)
		if len(line) > cloudflareMaxRedirectLine {
			return nil, fmt.Errorf("redirect for %s is %d characters; _redirects lines are limited to %d", r.Path, len(line), cloudflareMaxRedirectLine)
		}
		rd.WriteString(line)
		rd.WriteByte('\n')
	}

	// Header rules use one greedy splat each (Cloudflare allows a single
	// splat per rule). Canonical metadata under /dists must revalidate on
	// every `apt update`; by-hash entries live under /dists too and so
	// also get no-cache, which costs a conditional GET but is always
	// correct. Pool .debs are version-addressed and never change in place.
	hd := `# Generated by signpost export. Do not edit; the next export overwrites this file.
/dists/*
  Cache-Control: no-cache
/pubkey.gpg
  Cache-Control: no-cache
/release/*
  Cache-Control: no-cache
/pool/*
  Cache-Control: public, max-age=31536000, immutable
`
	return map[string][]byte{
		"_redirects": []byte(rd.String()),
		"_headers":   []byte(hd),
	}, nil
}
