package export

import (
	"fmt"
	"strings"
)

// NginxConfName is the file the "nginx" target writes at the output
// root. It is an http-context include holding a `map` from $uri to the
// upstream URL, with a commented server{} example. nginx serves it as a
// static file if the output root is the document root; it contains only
// the upstream URLs that the 302s already reveal.
const NginxConfName = "signpost-nginx.conf"

// nginxVar is the map's output variable.
const nginxVar = "$signpost_redirect"

type nginxTarget struct{}

func (nginxTarget) Name() string { return "nginx" }

func (nginxTarget) Emit(m *Manifest) (map[string][]byte, error) {
	// nginx matches plain map keys case-insensitively. Pool paths differing
	// only by case would silently collapse, so refuse that up front.
	folded := map[string]string{}
	for _, r := range m.Redirects {
		k := strings.ToLower(r.Path)
		if other, dup := folded[k]; dup {
			return nil, fmt.Errorf("redirect paths %s and %s differ only by case; nginx map keys are case-insensitive", other, r.Path)
		}
		folded[k] = r.Path
		// nginx interpolates $variables inside quoted map values.
		if strings.Contains(r.Location, "$") {
			return nil, fmt.Errorf("redirect %s: location %q contains '$', which nginx would interpolate", r.Path, r.Location)
		}
	}

	var b strings.Builder
	b.WriteString(`# Generated by signpost export. Do not edit; the next export overwrites this file.
#
# Include this file from the http {} context, then serve the export root
# with a server {} block like:
#
#   server {
#     listen 80;
#     server_name apt.example.com;
#     root /srv/apt;                      # the signpost export --out dir
#
#     if (` + nginxVar + `) { return 302 ` + nginxVar + `; }
#
#     location /dists/   { add_header Cache-Control "no-cache"; }
#     location /release/ { add_header Cache-Control "no-cache"; }
#     location = /pubkey.gpg { add_header Cache-Control "no-cache"; }
#     location /pool/    { add_header Cache-Control "public, max-age=31536000, immutable"; }
#   }
#
# Note: nginx matches plain map keys case-insensitively.

map $uri ` + nginxVar + ` {
    default "";
`)
	for _, r := range m.Redirects {
		fmt.Fprintf(&b, "    %q %q;\n", r.Path, r.Location)
	}
	b.WriteString("}\n")
	return map[string][]byte{NginxConfName: []byte(b.String())}, nil
}
