package export

import (
	"fmt"
	"strings"
)

// NginxConfName is the file the "nginx" target writes at the output
// root. It is an http-context include holding a `map` from $uri to the
// upstream URL, with a commented server{} example. nginx serves it as a
// static file if the output root is the document root; it contains only
// the upstream URLs that the 302s already reveal.
const NginxConfName = "signpost-nginx.conf"

// nginxVar is the map's output variable.
const nginxVar = "$signpost_redirect"

type nginxTarget struct{}

func (nginxTarget) Name() string { return "nginx" }

func (nginxTarget) Emit(m *Manifest) (map[string][]byte, error) {
	// nginx matches plain map keys case-insensitively. Pool paths differing
	// only by case would silently collapse, so refuse that up front.
	folded := map[string]string{}
	for _, r := range m.Redirects {
		k := strings.ToLower(r.Path)
		if other, dup := folded[k]; dup {
			return nil, fmt.Errorf("redirect paths %s and %s differ only by case; nginx map keys are case-insensitive", other, r.Path)
		}
		folded[k] = r.Path
		// nginx interpolates $variables inside quoted map values.
		if strings.Contains(r.Location, "$") {
			return nil, fmt.Errorf("redirect %s: location %q contains '$', which nginx would interpolate", r.Path, r.Location)
		}
	}

	p := m.PathPrefix
	var b strings.Builder
	b.WriteString("# Generated by signpost export. Do not edit; the next export overwrites this file.\n")
	b.WriteString("#\n")
	b.WriteString("# Include this file from the http {} context, then serve the export root\n")
	b.WriteString("# with a server {} block like:\n")
	b.WriteString("#\n")
	b.WriteString("#   server {\n")
	b.WriteString("#     listen 80;\n")
	b.WriteString("#     server_name apt.example.com;\n")
	b.WriteString("#     root /srv/apt;                      # the signpost export --out dir\n")
	b.WriteString("#\n")
	b.WriteString("#     if (" + nginxVar + ") { return 302 " + nginxVar + "; }\n")
	b.WriteString("#\n")
	b.WriteString("#     location " + p + "/dists/   { add_header Cache-Control \"no-cache\"; }\n")
	b.WriteString("#     location " + p + "/release/ { add_header Cache-Control \"no-cache\"; }\n")
	b.WriteString("#     location = " + p + "/pubkey.gpg { add_header Cache-Control \"no-cache\"; }\n")
	b.WriteString("#     location " + p + "/pool/    { add_header Cache-Control \"public, max-age=31536000, immutable\"; }\n")
	b.WriteString("#   }\n")
	b.WriteString("#\n")
	if p != "" {
		b.WriteString("# The repository is published under " + p + "/ (repository.base_url), so the\n")
		b.WriteString("# site tree lives at <out>" + p + "/ and every map key below carries that\n")
		b.WriteString("# prefix. To mount the subtree alone, use `location " + p + "/ { alias <out>" + p + "/; }`\n")
		b.WriteString("# instead of `root`; the map keys are unaffected since $uri includes the prefix.\n")
		b.WriteString("#\n")
	}
	b.WriteString("# Note: nginx matches plain map keys case-insensitively.\n")
	b.WriteString("\n")
	b.WriteString("map $uri " + nginxVar + " {\n")
	b.WriteString("    default \"\";\n")
	for _, r := range m.Redirects {
		fmt.Fprintf(&b, "    %q %q;\n", r.Path, r.Location)
	}
	b.WriteString("}\n")
	return map[string][]byte{NginxConfName: []byte(b.String())}, nil
}
