package sign

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ProtonMail/go-crypto/openpgp"
	"github.com/ProtonMail/go-crypto/openpgp/packet"
)

// EnsureKey is the auto-generate hook for signing.key_file.
//
// If a file exists at path: returns nil immediately (caller proceeds with
// the regular Load + secure-file checks).
//
// If no file exists: generates a fresh unencrypted RSA-2048 entity using
// uid as the OpenPGP User ID, writes the secret half to path with mode
// 0400, owned by the current uid, and returns nil.
//
// Idempotency: a second call after the file exists is a no-op.
//
// Auto-generated keys are unencrypted on purpose — there's no operator
// available at startup to type a passphrase. Encrypted keys must be
// provisioned manually.
func EnsureKey(path, uid string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", path, err)
	}

	if uid == "" {
		return fmt.Errorf("EnsureKey: uid is required to label the generated entity")
	}

	// Best-effort: ensure parent dir exists with 0700 so the file lands
	// somewhere predictable. Failure here is fatal.
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}

	name, email := splitUID(uid)
	entity, err := openpgp.NewEntity(name, "auto-generated by apt-signpost", email, &packet.Config{
		RSABits: 2048,
	})
	if err != nil {
		return fmt.Errorf("NewEntity: %w", err)
	}

	// Write to a tmp file first, then rename — same atomic-write discipline
	// internal/store uses for state files.
	tmp, err := os.CreateTemp(dir, ".keygen-*")
	if err != nil {
		return fmt.Errorf("create tmp: %w", err)
	}
	tmpName := tmp.Name()
	renamed := false
	defer func() {
		if !renamed {
			_ = os.Remove(tmpName)
		}
	}()

	if err := entity.SerializePrivate(tmp, &packet.Config{}); err != nil {
		tmp.Close()
		return fmt.Errorf("serialize private: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("sync: %w", err)
	}
	if err := tmp.Chmod(0o400); err != nil {
		tmp.Close()
		return fmt.Errorf("chmod: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename: %w", err)
	}
	renamed = true
	return nil
}

// splitUID parses "Name <email>" → ("Name", "email"). When no angle-bracket
// email segment is present, the whole string is treated as the name with
// an empty email — openpgp.NewEntity accepts that.
func splitUID(uid string) (name, email string) {
	uid = strings.TrimSpace(uid)
	open := strings.LastIndexByte(uid, '<')
	close := strings.LastIndexByte(uid, '>')
	if open >= 0 && close > open {
		return strings.TrimSpace(uid[:open]), strings.TrimSpace(uid[open+1 : close])
	}
	return uid, ""
}
